version: '3.0'

services:
  web:
    image: python:3.9-slim
    container_name: petition_api_web
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: petition_api_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petition_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
