# Generated by Django 4.2.15 on 2024-08-22 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiPetition',
            new_name='Petition',
        ),
        migrations.RenameModel(
            old_name='ApiSignature',
            new_name='Signature',
        ),
    ]
