# Generated by Django 4.2.15 on 2024-09-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_apipetition_petition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
